// src/data/sampleData.js
export const initialEmployees = [
  {
    id: 1,
    name: "Brooklyn Simmons",
    email: "brook-simms@mail.com",
    phone: "(+62) 928 7273 7262",
    department: "Design",
    jobTitle: "Creative Director",
    contract: "Onsite - Fulltime",
    attendance: "120h 32m",
    avatar: "BS",
  },
  {
    id: 2,
    name: "Cody Fisher",
    email: "cody_fisher99@mail.com",
    phone: "(+62) 928 7273 7262",
    department: "Development",
    jobTitle: "Head of Development",
    contract: "Onsite - Fulltime",
    attendance: "120h 32m",
    avatar: "CF",
  },
  {
    id: 3,
    name: "Ralph Edwards",
    email: "ralph_uxdsg@mail.com",
    phone: "(+62) 928 7273 7262",
    department: "Design",
    jobTitle: "Sr. UX Designer",
    contract: "Onsite - Fulltime",
    attendance: "120h 32m",
    avatar: "RE",
  },
  {
    id: 4,
    name: "Bessie Cooper",
    email: "bess_coop@mail.com",
    phone: "(+62) 928 7273 7262",
    department: "HR",
    jobTitle: "Sr. HR",
    contract: "Onsite - Fulltime",
    attendance: "120h 32m",
    avatar: "BC",
  },
  {
    id: 5,
    name: "Leslie Alexander",
    email: "alexander_le@mail.com",
    phone: "(+62) 928 7273 7262",
    department: "PM",
    jobTitle: "Head of PM",
    contract: "Onsite - Fulltime",
    attendance: "120h 32m",
    avatar: "LA",
  },
];

export const departments = [
  { id: 1, name: "Design", count: 2, color: "green" },
  { id: 2, name: "Development", count: 1, color: "blue" },
  { id: 3, name: "HR", count: 1, color: "purple" },
  { id: 4, name: "PM", count: 1, color: "orange" },
];
